name: Build to Production

on:
  pull_request:
    types: [closed]
    branches: ["main"]
#   push:
#     branches: ["main"]
#   pull_request:
#     branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    if: github.event.pull_request.merged

    steps:
#       - uses: actions/checkout@v3

#       # - name: Configure AWS Credentials
#       #   uses: aws-actions/configure-aws-credentials@v2
#       #   with:
#       #     role-to-assume: arn:aws:iam::762417892045:role/github-actions
#       #     aws-region: us-east-1

#       # - name: Login to Amazon ECR Private
#       #   id: login-ecr
#       #   uses: aws-actions/amazon-ecr-login@v1

#       - name: Build
#         env:
#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           ECR_REPOSITORY: 5ob-api
#         run: |
#           echo $IMAGE_TAG
#           docker build .

#       - name: Bump version and push tag
#         id: tagging
#         uses: K-Phoen/semver-release-action@master
#         with:
#           release_branch: main
#           release_strategy: tag
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#       - name: Push container to ECR
#         run: |
#           echo ${{ steps.tagging.outputs.tag }}
#           # docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


 
      - name: Tag
        id: tagging
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push container to ECR
        run: |
          echo ${{ steps.tagging.outputs.tag }}
          
        
