name: Build to Production

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     role-to-assume: arn:aws:iam::762417892045:role/github-actions
      #     aws-region: us-east-1

      # - name: Login to Amazon ECR Private
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      - name: Build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: 5ob-api
          IMAGE_TAG: v${{ vars.MAJOR_VERSION_NUMBER }}.${{ vars.MINOR_VERSION_NUMBER }}.0
        run: |
          vars.MAJOR_VERSION_NUMBER = vars.MAJOR_VERSION_NUMBER + 1
          echo $IMAGE_TAG
          docker build .

      - name: Bump version and push tag
        id: tagging
        uses: darioblanco/bump-semver@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          defaultBump: minor

      - name: Push container to ECR
        run: |
          echo ${{ steps.tagging.outputs.tag }}
          # docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
